#! /bin/bash

source /opt/ros/kinetic/setup.bash
source ~/catkin_ws/devel/setup.bash

killall roscore > /dev/null 2>&1
killall gzserver > /dev/null 2>&1
killall gzclient > /dev/null 2>&1
node_manager
killall roscore > /dev/null 2>&1
killall gzserver > /dev/null 2>&1
killall gzclient > /dev/null 2>&1
