#! /bin/bash

#set default values
DEP="--no-deps"
COL="--force-color"
STATUS="| tee"
PRINT=false
UNI=true

#check arguments
for ARG in "$@"
do

  #check for help
  if [ $ARG = "-h" ] || [ $ARG = "--help" ]
  then
    echo "Simple script for building the package corresponding to the current directory"
    echo "If multiple errors are encountered the first one is reprinted last"
    echo "Optional arguments:"
    echo "    -h or --help: this help message"
    echo "    -d or --depends: builds dependences"
    echo "    -c or --no-color: removes color information from output"
    echo "    -s or --no-status: disables status updates until build finished"
    echo "    -u or --no-unicode: removes unicode characters (only works in combination with -s)"
    exit 1
  fi

  #check for dependences flag
  if [ $ARG = "-d" ] || [ $ARG = "--depends" ]
  then
    DEP=""
  fi 

  #check for no color flag
  if [ $ARG = "-c" ] || [ $ARG = "--no-color" ]
  then
    COL="--no-color"
  fi 

  #check for no status flag
  if [ $ARG = "-s" ] || [ $ARG = "--no-status" ]
  then
    STATUS="--no-status >>"
    PRINT=true
  fi 

  #check for no unicode flag
  if [ $ARG = "-u" ] || [ $ARG = "--no-unicode" ]
  then
    UNI=false
  fi 
done

#get package to build
PACKAGE="$(catkin list --this)"
PACKAGE=${PACKAGE:2}

echo "Building $PACKAGE..."
echo

#get ready to grab output
TEMP=$(mktemp)

#build and catch output
eval "catkin build $PACKAGE $DEP $COL $STATUS $TEMP 2>&1"

#print output if status updates were suppressed (skips Workspace info)
if [ $PRINT ]
then
  #strip unicode (unfortunately python outputs them as ? so all ? will also be removed)
  if [ !UNI ]
  then
    sed -i 's/?//g' $TEMP
  fi
  
  OUT_START=$(grep -n -m 1 "\[build\]" $TEMP | cut -f1 -d:)
  tail -n +${OUT_START} $TEMP
fi

#check output for errors
ERR_START=$(grep -n -m 1 "Errors" $TEMP | cut -f1 -d:)

echo

#if multiple errors reprint first one
if [ "$ERR_START" != "" ]
then
  ERR_END=$(grep -n -m2 "error:\|note:" $TEMP)
  NUM_ERR=$(wc -l <<<"$(echo "$ERR_END")")
  if [ "$NUM_ERR" != 1 ]
  then
    ERR_END=$(echo "$ERR_END" | tail -n1 | cut -f1 -d:)
  else
    ERR_END=$(grep -n -m2 "Error " $TEMP)
  fi

  echo "Errors encountered, reprinting first error:"
  echo "................................................................"
  awk -v s="$ERR_START" -v e="$ERR_END" 'NR>s&&NR<e' $TEMP
  echo
  echo "FAILED BUILD"
else 
  echo "SUCESSFUL BUILD"
fi

#clean up
rm $TEMP